Fix initialization of Rails logger (again)
This returns the logger objects initialization back to being very early,
since there are certain code paths (like rake tasks) that do not load
the environment, but still need the loggers defined.

For example, it fixes the following issue with `rake evm:db:start`

    Starting EVM server daemon...
    rake aborted!
    NoMethodError: undefined method `logger' for Vmdb:Module
    /var/www/miq/vmdb/lib/vmdb/logging.rb:56:in `logger'
    /var/www/miq/vmdb/lib/vmdb/logging.rb:41:in `block (2 levels) in <class:LogProxy>'
    /var/www/miq/vmdb/lib/evm_database_ops.rb:127:in `start'
    /var/www/miq/vmdb/lib/tasks/evm_dba.rake:24:in `start'
    /var/www/miq/vmdb/lib/tasks/evm_dba.rake:89:in `block (3 levels) in <top (required)>'
    /var/www/miq/vmdb/lib/tasks/evm_dba.rake:69:in `block (3 levels) in <top (required)>'
    Tasks: TOP => evm:db:silent_start


(transferred from ManageIQ/manageiq@8954b3fe08ce747a058984a394dba0023f57703f)