fix logger issues
Ruby changed the way they report backtraces

```diff
- app/controllers/api/base_controller/logger.rb:61:in `Api::BaseController::Logger#api_get_method_name'
+ app/controllers/api/base_controller/logger.rb:61:in 'Api::BaseController::Logger#api_get_method_name'
```

The code was no longer able to determine the method name in recent ruby versions.
This meant that it would use the method (symbol) and `Symbol#sub` doesn't work.

So we did 2 things:

- match backtraces for older rubies and newer versions.
- Convert `method` to a String so `String#sub` will work.

Reproducer
==========

```
curl -k -u admin:smartvm --basic http://localhost:3000/api/service_catalogs
```

Before
======

```
Causes:
NoMethodError (undefined method 'sub' for an instance of Symbol)

app/controllers/api/base_controller/logger.rb:61:in 'Api::BaseController::Logger#api_get_method_name'
```

fixup! fix logger issues